### ISSUE TITLE
Hardcoded php path

### ISSUE THREAD

**Issue by dododedodonl** [3mmarg97/LaravelStorm#1]
It would be nice if it was possible to set the path to php so one can run a different version than the system default.

**Comment by ammardev** [comment]
Do you mean you want to choose a custom php path  like this :
![image](https://user-images.githubusercontent.com/16087389/27758697-2e98f780-5e24-11e7-9240-a6fbcc5f806c.png)
If you want something like that you can do it from phpstorm / intellij Settings .
From : File menu > Settings > Languages & Frameworks > PHP 
Press the button next  to the drop down and the above dialog will appear .

![image](https://user-images.githubusercontent.com/16087389/27758717-cf4f9fc6-5e24-11e7-874e-97d32c853e21.png)

**Comment by dododedodonl** [comment]
Yes, or just a field in which I can paste the path to php. The problem I run into is that the run command does not work because it is hardcoded to the system default php (which is too old).

<img width="575" alt="schermafbeelding 2017-07-01 om 10 56 35" src="https://user-images.githubusercontent.com/100052/27760585-e26a3c48-5e4b-11e7-89fc-440e3bd6e070.png">

I would like that to be configurable to `/path/to/php artisan serve --host=localhost --port=8000` than the plugin will also work for me.

**Comment by ammardev** [comment]
I should get the command from the PhpStorm settings. But instead I sent `php` command without getting it from the settings . I will fix it soon . Thanks for reporting

**Comment by ammardev** [comment]
Solved on commit https://github.com/3mmarg97/LaravelStorm/commit/a763cb0d2ff0a716b018d866f862bba35b145e18 (Not released yet)
