### ISSUE TITLE
LaravelStorm is not compatible with phpstorm 2020.3

### ISSUE THREAD

**Issue by RazeSoldier** [3mmarg97/LaravelStorm#4]
With the release of [phpstorm 2020.3](https://www.jetbrains.com/phpstorm/whatsnew/). Whenever start it, the event log will show an error message.
```
Plugin 'LaravelStorm' (version 1.1) was explicitly marked as incompatible with the current version of the IDE
```

**Comment by ammardev** [comment]
Hello, This project is no longer maintained.
I don't use Phpstorm anymore so I don't really know about their latest plugin API updates.

You are free to fork this project and make a PR.
